### ISSUE TITLE
Question: Will you provide unit tests?

### ISSUE THREAD

**Issue by penguinpee** [mdmintz/pynose#25]
I was looking into introducing `pynose` to Fedora. It seems a viable drop-in replacement for the no longer maintained [nose](https://github.com/nose-devs/nose).

In a preliminary discussion the issue of `pynose` not providing any tests came up. Ye olde 👃 did have unit tests. Are you planning on providing unit tests in the future? While not mandatory for the software to be packaged for Fedora, where available we do run them in order to detect potential issues early.

Somewhat related: The documentation link on PyPI sends you to the documentation of legacy `nose`. While most of it probably still applies, it's also a bit confusing. Not the least because there it still mentions _Current version: 1.3.7_, which links back to `nose`.

**Comment by mdmintz** [comment]
Thanks for catching the old documentation link. It's been updated: https://github.com/mdmintz/pynose/commit/bf22fdcaadf1ec772738f655e77d7aa3e5e78552. (Although I won't ship a new release just for the PyPI Documentation link to update, but it will get into the next release once there is something meaningful to change).

There are some basic unit tests here: https://github.com/mdmintz/pynose/actions (The previous ones were largely a mess, so I run a lot of extra tests separately before shipping any changes.)

**Comment by penguinpee** [comment]
Thanks for the quick response. I agree, no need to push another update just for the documentation link. That's more cosmetic, I suppose.

Regarding GH Actions, it's good to see that there is at least some testing going on. However, I was referring to tests we can run downstream. I do realize that may pose a chicken and egg problem if you wanted to test your own code with `pynose`.

**Comment by mdmintz** [comment]
I run lots of `pynose` tests on https://github.com/seleniumbase/SeleniumBase for the tests in the `examples/` folder. It provides lots of coverage. (Although I use `pytest` mostly, I make sure to maintain backwards compatibility for both.)

**Comment by penguinpee** [comment]
I just ran `nosetests -v` on `SeleniumBase/examples`. No major issue encountered.

However, some basic unit tests for testing `pynose` itself would be very much appreciated. It helps us detecting potential issues with a package early. That could be updated dependencies or other system wide changes.

Maybe something to consider for the long run. Thanks again for answering my questions.
