### ISSUE TITLE
Release new version to PyPI with the updated license

### ISSUE THREAD

**Issue by kulikjak** [mdmintz/pynose#35]
Hi @mdmintz, thank you (and others who helped) for resolving all the license issues.

Now that that's solved, can we get a new version of pynose? Currently, pynose is in this in-between state where PyPi lists it as MIT licensed (because the last version was), and the repo as LGPL (and so if somebody checks on different places what the license is, they won't get a definitive answer). A new version can solve that.

Thanks!

**Comment by mdmintz** [comment]
Good morning. (It's morning here, at least.)
I'll get a new version of `pynose` on PyPI today.

**Comment by mdmintz** [comment]
Might be one more change needed first. Checking on https://github.com/mdmintz/pynose/issues/28 with incorporating Git History too.

These PRs were already merged:
* https://github.com/mdmintz/pynose/pull/30
* https://github.com/mdmintz/pynose/pull/32
* https://github.com/mdmintz/pynose/pull/34

As for changing Git History to include all the original history of `nose`, I'm checking with the process for that, and also whether or not that's required. I'm also going to see how other repos in a similar situation handled that.

This might push back the PyPI release by one day until Friday afternoon Eastern Standard Time (tomorrow).

**Comment by mdmintz** [comment]
Version `1.5.2` has been released.
